### ISSUE TITLE
Brief description of old / new style relations?

### ISSUE THREAD

**Issue by IknowJoseph** [osmlab/fixing-polygons-in-osm#20]
Could such a description be added to the home page? I'm not a follower of current tagging standards, so would like a quick / easy / obvious explanation of what new and old style means. One has the tags on the ways and one on the relation?

**Comment by joto** [comment]
I have made the explanation that was on the home page a bit more obvious and I have now linked directly from the home page to several pages with background information. Yes, *old style* meand the tags are on the ways instead of on the relations, but there is more to it, so a quick explanation is not enough, you have to click through to the details and read and understand all the details.

**Comment by IknowJoseph** [comment]
Thanks, that's really helpful. I've got a couple of suggestions for the
text, but as you have it is already an improvement:

Of the over 220 million (multi)polygons in OSM more than 100,000 contain
mapping errors of one kind or another, and about 250,000 are tagged "old
style", with tags on the outer ways instead of on the relation itself.
These factors make multipolygon tagging, and processing, much more
complicated and much more expensive than it needs to be.
